fix: ensure CSR works with a capped collection
The findOneAndDelete() operation is not authorized on a capped
collection, so the connection state recovery would always fail when
fetching the session.

> MongoServerError: cannot remove from a capped collection

Related: https://github.com/socketio/socket.io-mongo-adapter/issues/20